version: '3'
services:
  laravel:
    image: 'laravelsail/php74-composer:latest'
    user: 'laravel'
    working_dir: /var/www/html
    volumes:
      - '.:/var/www/html'
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    networks:
      - sail
    depends_on:
      - mysql
  mysql:
    image: 'mysql:8.0'
    networks:
      - sail
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'sailmysql:/var/lib/mysql'
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_USERNAME: '${DB_USERNAME}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    depends_on:
      - mysql
    networks:
      - sail
networks:
  sail:
    driver: bridge
volumes:
  sailmysql:
    driver: local
