version: '3.8'

services:
  app:
    build:
      context: ./docker/php
    container_name: iron_crm
    volumes:
      - ./:/var/www
    working_dir: /var/www
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  node:
    image: node:14
    container_name: laravel_node
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8080:8080"
    command: sh -c "npm install && npm run hot"
    depends_on:
      - app

  mysql:
    image: mysql:8
    container_name: laravel_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
