<?php

return [
    'KASPI_API_KEY' => env('KASPI_API_KEY'),
    'KASPI_API_BASE_URL' => env('KASPI_API_BASE_URL'),
    'KASPI_MERCHANT_LOGIN' => env('KASPI_MERCHANT_LOGIN'),
    'KASPI_MERCHANT_PASSWORD' => env('KASPI_MERCHANT_PASSWORD'),
];
